[project]
name = "energy"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "Flask>=3.1.0",
    "numpy>=2.2.2"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["main"]
exclude = []
namespaces = false
